import {
    Building,
    // CalendarDays,
    ClipboardList,
    DollarSign,
    DoorOpen,
    // Home,
    Layers,
    Percent,
    Receipt,
    TowerControl,
    Wrench,
    BarChart2,
    UserSearch,
    FileText,
    Banknote,
    Home,
    KeyRound,
    // Globe,
    TrendingUp,
    HardHat,
    ClipboardX,
    Download, Network,
    FolderCog,
    ShieldCheck,
    Files,
    // Network,
} from "lucide-react";
import {
    IconFolder,
    IconLayoutDashboard,
} from "@tabler/icons-react";
import type {SidebarContribution} from "@coreModule/clients/panel/moduleContributions/sidebarContribution.types.ts";
import type {NavGroup, NavItem} from "@coreModule/helpers/panel/sidebarNav.types.ts";
import type {ResolveLanguageKey} from "@coreModule/helpers/hocs/withLanguage.tsx";

const propertyManagementSidebarContribution: SidebarContribution = {
    id: "propertyManagement",
    order: 20,
    getNavGroups(resolveLanguageKey: ResolveLanguageKey): NavGroup[] {
        const items: NavItem[] = [
            {
                title: resolveLanguageKey("menus.realEstate.systemMap.title"),
                url: "/realEstate/systemmap",
                icon: Network,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.overview.title"),
                url: "/realEstate/overview",
                icon: IconLayoutDashboard,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.dashboard.title"),
                url: "/realEstate/dashboard",
                icon: TowerControl,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.cockpit.title"),
                url: "/realEstate/cockpit",
                icon: BarChart2,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.projects.title"),
                url: "/realEstate/projects",
                icon: IconFolder,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.edifices.title"),
                url: "/realEstate/edifices",
                icon: Building,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.floors.title"),
                url: "/realEstate/floors",
                icon: Layers,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.units.title"),
                url: "/realEstate/units",
                icon: DoorOpen,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.development.title"),
                icon: FolderCog,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.landParcels.title"), url: "/realEstate/landParcels", icon: Files, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.feasibilityStudies.title"), url: "/realEstate/feasibilityStudies", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.projectDocuments.title"), url: "/realEstate/projectDocuments", icon: Files, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.permits.title"), url: "/realEstate/permits", icon: ShieldCheck, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.designStages.title"), url: "/realEstate/designStages", icon: Layers, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.consultantAppointments.title"), url: "/realEstate/consultantAppointments", icon: UserSearch, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.feeCalculations.title"), url: "/realEstate/feeCalculations", icon: Percent, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.delivery.title"),
                icon: HardHat,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.milestones.title"), url: "/realEstate/milestones", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.scheduleTasks.title"), url: "/realEstate/scheduleTasks", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.constructionUpdates.title"), url: "/realEstate/constructionUpdates", icon: HardHat, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.rfis.title"), url: "/realEstate/rfis", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.submittals.title"), url: "/realEstate/submittals", icon: Files, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.variationOrders.title"), url: "/realEstate/variationOrders", icon: Wrench, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.workPackages.title"), url: "/realEstate/workPackages", icon: FolderCog, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.constructionContracts.title"), url: "/realEstate/constructionContracts", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.progressClaims.title"), url: "/realEstate/progressClaims", icon: DollarSign, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.cost.title"),
                icon: Receipt,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.costClassifications.title"), url: "/realEstate/costClassifications", icon: Layers, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.budgets.title"), url: "/realEstate/budgets", icon: Banknote, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.boqItems.title"), url: "/realEstate/boqItems", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.estimateComparison.title"), url: "/realEstate/estimateComparison", icon: BarChart2, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.costControl.title"), url: "/realEstate/costControl", icon: BarChart2, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.costCommitments.title"), url: "/realEstate/costCommitments", icon: Receipt, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.finance.unitCosts.title"), url: "/realEstate/unitCosts", icon: Receipt, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.tendering.title"),
                icon: Files,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.specifications.title"), url: "/realEstate/specifications", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.specificationItems.title"), url: "/realEstate/specificationItems", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.tenders.title"), url: "/realEstate/tenders", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.tenderInvitations.title"), url: "/realEstate/tenderInvitations", icon: UserSearch, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.bids.title"), url: "/realEstate/bids", icon: DollarSign, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.bidLines.title"), url: "/realEstate/bidLines", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.bidComparison.title"), url: "/realEstate/bidComparison", icon: BarChart2, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.financeApproval.title"),
                icon: ShieldCheck,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.approvalWorkflows.title"), url: "/realEstate/approvalWorkflows", icon: ShieldCheck, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.approvalRequests.title"), url: "/realEstate/approvalRequests", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.contractorInvoices.title"), url: "/realEstate/contractorInvoices", icon: Receipt, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.incomingInvoices.title"), url: "/realEstate/incomingInvoices", icon: Download, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.liquidityPlans.title"), url: "/realEstate/liquidityPlans", icon: TrendingUp, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.liquidityLines.title"), url: "/realEstate/liquidityLines", icon: DollarSign, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.facilityMgmt.title"),
                icon: HardHat,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.assets.title"), url: "/realEstate/assets", icon: Building, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.maintenancePlans.title"), url: "/realEstate/maintenancePlans", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.maintenanceWorkOrders.title"), url: "/realEstate/maintenanceWorkOrders", icon: Wrench, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.bimIntegrations.title"),
                icon: Network,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.bimModels.title"), url: "/realEstate/bimModels", icon: Files, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.bimQuantities.title"), url: "/realEstate/bimQuantities", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.qualityHse.title"),
                icon: ClipboardX,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {title: resolveLanguageKey("menus.realEstate.planMarkups.title"), url: "/realEstate/planMarkups", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.inspections.title"), url: "/realEstate/inspections", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.inspectionChecklistTemplates.title"), url: "/realEstate/inspectionChecklistTemplates", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.snags.title"), url: "/realEstate/snags", icon: ClipboardX, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.siteDiaries.title"), url: "/realEstate/siteDiaries", icon: FileText, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.safetyIncidents.title"), url: "/realEstate/safetyIncidents", icon: ShieldCheck, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.warranties.title"), url: "/realEstate/warranties", icon: ShieldCheck, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.handoverPackages.title"), url: "/realEstate/handoverPackages", icon: Files, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                    {title: resolveLanguageKey("menus.realEstate.commissioningRecords.title"), url: "/realEstate/commissioningRecords", icon: ClipboardList, permissions: [], usersPermissions: [], atLeastOnePermission: true},
                ],
            },
            {
                title: resolveLanguageKey("menus.realEstate.leads.title"),
                url: "/realEstate/leads",
                icon: UserSearch,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.modificationRequests.title"),
                url: "/realEstate/modificationRequests",
                icon: Wrench,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.reservations.title"),
                url: "/realEstate/reservations",
                icon: ClipboardList,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.sales.title"),
                url: "/realEstate/sales",
                icon: DollarSign,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.contractsHub.title"),
                url: "/realEstate/contractsHub",
                icon: FileText,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.commissions.title"),
                url: "/realEstate/commissions",
                icon: Percent,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.ownersAndRentals.title"),
                icon: KeyRound,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.realEstate.rentalsHub.title"),
                        url: "/realEstate/rentalsHub",
                        icon: Home,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.realEstate.leases.title"),
                        url: "/realEstate/leases",
                        icon: FileText,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.realEstate.rentalPayments.title"),
                        url: "/realEstate/rentalPayments",
                        icon: Banknote,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
            {
                title: resolveLanguageKey("menus.reports.title"),
                icon: BarChart2,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.reports.groupDashboard.title"),
                        url: "/realEstate/groupDashboard",
                        icon: Network,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.agentReport.title"),
                        url: "/realEstate/agentReport",
                        icon: BarChart2,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.roi.title"),
                        url: "/realEstate/roi",
                        icon: TrendingUp,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.erpExport.title"),
                        url: "/realEstate/erpExport",
                        icon: Download,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
            {
                title: resolveLanguageKey("menus.finance.title"),
                icon: Receipt,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.finance.unitCosts.title"),
                        url: "/realEstate/unitCosts",
                        icon: Receipt,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
        ];

        return [
            {
                title: resolveLanguageKey("menus.realEstate.title"),
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items,
            },
        ];
    },
};

export default propertyManagementSidebarContribution;
