import {
    Building,
    // CalendarDays,
    ClipboardList,
    DollarSign,
    DoorOpen,
    // Home,
    Layers,
    Percent,
    Receipt,
    TowerControl,
    Wrench,
    BarChart2,
    UserSearch,
    FileText,
    Banknote,
    Home,
    KeyRound,
    // Globe,
    TrendingUp,
    HardHat,
    ClipboardX,
    Download, Network,
    // Network,
} from "lucide-react";
import {
    IconFolder,
    IconLayoutDashboard,
} from "@tabler/icons-react";
import type {SidebarContribution} from "@coreModule/clients/panel/moduleContributions/sidebarContribution.types.ts";
import type {NavGroup, NavItem} from "@coreModule/helpers/panel/sidebarNav.types.ts";
import type {ResolveLanguageKey} from "@coreModule/helpers/hocs/withLanguage.tsx";

const propertyManagementSidebarContribution: SidebarContribution = {
    id: "propertyManagement",
    order: 20,
    getNavGroups(resolveLanguageKey: ResolveLanguageKey): NavGroup[] {
        const items: NavItem[] = [
            {
                title: resolveLanguageKey("menus.realEstate.overview.title"),
                url: "/realEstate/overview",
                icon: IconLayoutDashboard,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.dashboard.title"),
                url: "/realEstate/dashboard",
                icon: TowerControl,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.projects.title"),
                url: "/realEstate/projects",
                icon: IconFolder,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.edifices.title"),
                url: "/realEstate/edifices",
                icon: Building,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.floors.title"),
                url: "/realEstate/floors",
                icon: Layers,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.units.title"),
                url: "/realEstate/units",
                icon: DoorOpen,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.leads.title"),
                url: "/realEstate/leads",
                icon: UserSearch,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.inspections.title"),
                url: "/realEstate/inspections",
                icon: ClipboardList,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.modificationRequests.title"),
                url: "/realEstate/modificationRequests",
                icon: Wrench,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.reservations.title"),
                url: "/realEstate/reservations",
                icon: ClipboardList,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.sales.title"),
                url: "/realEstate/sales",
                icon: DollarSign,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.contractsHub.title"),
                url: "/realEstate/contractsHub",
                icon: FileText,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.commissions.title"),
                url: "/realEstate/commissions",
                icon: Percent,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            // {
            //     title: resolveLanguageKey("menus.realEstate.unitAvailability.title"),
            //     url: "/realEstate/units/availability",
            //     icon: CalendarDays,
            //     permissions: [],
            //     usersPermissions: [],
            //     atLeastOnePermission: true,
            // },
            {
                title: resolveLanguageKey("menus.realEstate.constructionUpdates.title"),
                url: "/realEstate/constructionUpdates",
                icon: HardHat,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.snags.title"),
                url: "/realEstate/snags",
                icon: ClipboardX,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
            },
            {
                title: resolveLanguageKey("menus.realEstate.ownersAndRentals.title"),
                icon: KeyRound,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.realEstate.rentalsHub.title"),
                        url: "/realEstate/rentalsHub",
                        icon: Home,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.realEstate.leases.title"),
                        url: "/realEstate/leases",
                        icon: FileText,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.realEstate.rentalPayments.title"),
                        url: "/realEstate/rentalPayments",
                        icon: Banknote,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
            {
                title: resolveLanguageKey("menus.reports.title"),
                icon: BarChart2,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.reports.groupDashboard.title"),
                        url: "/realEstate/groupDashboard",
                        icon: Network,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.agentReport.title"),
                        url: "/realEstate/agentReport",
                        icon: BarChart2,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.roi.title"),
                        url: "/realEstate/roi",
                        icon: TrendingUp,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                    {
                        title: resolveLanguageKey("menus.reports.erpExport.title"),
                        url: "/realEstate/erpExport",
                        icon: Download,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
            {
                title: resolveLanguageKey("menus.finance.title"),
                icon: Receipt,
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items: [
                    {
                        title: resolveLanguageKey("menus.finance.unitCosts.title"),
                        url: "/realEstate/unitCosts",
                        icon: Receipt,
                        permissions: [],
                        usersPermissions: [],
                        atLeastOnePermission: true,
                    },
                ],
            },
        ];

        return [
            {
                title: resolveLanguageKey("menus.realEstate.title"),
                permissions: [],
                usersPermissions: [],
                atLeastOnePermission: true,
                items,
            },
        ];
    },
};

export default propertyManagementSidebarContribution;
