import type {SystemMapDataset} from "@coreModule/components/custom/systemMap/systemMap.types.ts";

/**
 * Hand-curated System Map for propertyManagement (panel menu: realEstate).
 * Keep next to schema changes — living architecture view for /realEstate/systemmap.
 */

export const PROPERTY_MANAGEMENT_SYSTEM_MAP: SystemMapDataset = {
    clusters: ["portfolio", "sales", "leasing", "delivery", "cost", "quality"],
    nodes: [
        // ── Portfolio ───────────────────────────────────────────────
        {
            id: "Project",
            label: "Project",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Top-level development / portfolio container for edifices, sales, and delivery.",
            keyFields: ["name", "description", "mainImage", "saleCommissionRatePercent"],
            apiPath: "/api/realEstate/project",
            panelRoute: "/realEstate/projects",
            position: {x: 40, y: 40},
        },
        {
            id: "Edifice",
            label: "Edifice",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Building within a project — address, investment value, constructors, unit types.",
            keyFields: ["name", "address", "investmentValue", "pricePerMeterSquared", "project"],
            apiPath: "/api/realEstate/edifice",
            panelRoute: "/realEstate/edifices",
            position: {x: 40, y: 180},
        },
        {
            id: "Floor",
            label: "Floor",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Level inside an edifice; groups units.",
            keyFields: ["name", "level", "edifice", "project"],
            apiPath: "/api/realEstate/floor",
            panelRoute: "/realEstate/floors",
            position: {x: 40, y: 320},
        },
        {
            id: "Unit",
            label: "Unit",
            cluster: "portfolio",
            module: "propertyManagement",
            description:
                "Sellable/rentable space. Status: available → reserved → sold | rented (also unavailable).",
            keyFields: ["unitNumber", "area", "price", "status", "floor", "edifice", "unitType"],
            apiPath: "/api/realEstate/unit",
            panelRoute: "/realEstate/units",
            position: {x: 40, y: 460},
        },
        {
            id: "UnitType",
            label: "UnitType",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Typology template (e.g. 2BR) configured under tenancy settings.",
            keyFields: ["name", "category", "area"],
            apiPath: "/api/realEstate/unitType",
            panelRoute: "/tenancy/systemSettings/unitTypes",
            position: {x: 280, y: 320},
        },
        {
            id: "UnitTypeCategory",
            label: "UnitTypeCategory",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Grouping for unit types (apartment, retail, parking…).",
            keyFields: ["name"],
            apiPath: "/api/realEstate/unitTypeCategory",
            panelRoute: "/tenancy/systemSettings/unitTypeCategories",
            position: {x: 280, y: 180},
        },
        {
            id: "Constructor",
            label: "Constructor",
            cluster: "portfolio",
            module: "propertyManagement",
            description: "Contractor/builder party used by edifices, work packages, and contracts.",
            keyFields: ["name", "company"],
            apiPath: "/api/realEstate/constructor",
            panelRoute: "/tenancy/systemSettings/constructors",
            position: {x: 280, y: 40},
        },

        // ── Sales ───────────────────────────────────────────────────
        {
            id: "Lead",
            label: "Lead",
            cluster: "sales",
            module: "propertyManagement",
            description: "Sales pipeline interest linked to project and optionally a unit.",
            keyFields: ["status", "project", "unit", "user", "currency"],
            apiPath: "/api/realEstate/lead",
            panelRoute: "/realEstate/leads",
            position: {x: 560, y: 40},
        },
        {
            id: "Reservation",
            label: "Reservation",
            cluster: "sales",
            module: "propertyManagement",
            description: "Deposit hold on a unit — sets unit to reserved; can convert to Sale.",
            keyFields: ["unit", "deposit", "expiration", "status", "paid", "client"],
            apiPath: "/api/realEstate/unit/reservation",
            panelRoute: "/realEstate/reservations",
            actions: ["expire", "cancel", "convert"],
            position: {x: 560, y: 180},
        },
        {
            id: "Sale",
            label: "Sale",
            cluster: "sales",
            module: "propertyManagement",
            description: "Unit sale — cash or payment_plan; marks unit sold; optional PaymentPlan.",
            keyFields: ["unit", "buyer", "paymentType", "finalPrice", "approvalStatus", "reservation?"],
            apiPath: "/api/realEstate/unit/sale",
            panelRoute: "/realEstate/sales",
            actions: ["approve", "handover", "titleTransfer"],
            position: {x: 560, y: 340},
        },
        {
            id: "PaymentPlan",
            label: "PaymentPlan",
            cluster: "sales",
            module: "propertyManagement",
            description: "Installment schedule attached to a payment_plan Sale.",
            keyFields: ["sale", "installments[]", "status", "interest"],
            apiPath: "/api/realEstate/paymentPlan",
            panelRoute: "/realEstate/sales",
            position: {x: 800, y: 340},
        },
        {
            id: "Commission",
            label: "Commission",
            cluster: "sales",
            module: "propertyManagement",
            description: "Agent commission from a sale or reservation.",
            keyFields: ["amount", "status", "sale?", "reservation?", "user"],
            apiPath: "/api/realEstate/commission",
            panelRoute: "/realEstate/commissions",
            position: {x: 800, y: 180},
        },

        // ── Leasing ─────────────────────────────────────────────────
        {
            id: "Lease",
            label: "Lease",
            cluster: "leasing",
            module: "propertyManagement",
            description: "Rental agreement — sets unit to rented; terminate/expire releases unit.",
            keyFields: ["unit", "tenant", "startDate", "endDate", "monthlyRent", "deposit", "status"],
            apiPath: "/api/realEstate/lease",
            panelRoute: "/realEstate/leases",
            actions: ["terminate", "expire"],
            position: {x: 560, y: 520},
        },
        {
            id: "RentalPayment",
            label: "RentalPayment",
            cluster: "leasing",
            module: "propertyManagement",
            description: "Scheduled rent installment: pending → paid | overdue | waived.",
            keyFields: ["lease", "unit", "dueDate", "amount", "status"],
            apiPath: "/api/realEstate/rentalPayment",
            panelRoute: "/realEstate/rentalPayments",
            actions: ["markPaid", "waive"],
            position: {x: 800, y: 520},
        },

        // ── Delivery ────────────────────────────────────────────────
        {
            id: "LandParcel",
            label: "LandParcel",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Land asset tied to early project planning.",
            keyFields: ["project", "area", "status"],
            apiPath: "/api/realEstate/landParcel",
            panelRoute: "/realEstate/landParcels",
            position: {x: 1080, y: 40},
        },
        {
            id: "FeasibilityStudy",
            label: "FeasibilityStudy",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Pre-construction feasibility assessment for a project.",
            keyFields: ["project", "status", "findings"],
            apiPath: "/api/realEstate/feasibilityStudy",
            panelRoute: "/realEstate/feasibilityStudies",
            position: {x: 1320, y: 40},
        },
        {
            id: "Permit",
            label: "Permit",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Regulatory permit with expiry tracking (cron reminders).",
            keyFields: ["project", "type", "status", "expiresAt"],
            apiPath: "/api/realEstate/permit",
            panelRoute: "/realEstate/permits",
            position: {x: 1080, y: 160},
        },
        {
            id: "ProjectDocument",
            label: "ProjectDocument",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Drawing/spec/report register with revisions; required deliverables gate DesignStage completion.",
            keyFields: ["project", "discipline", "documentType", "revision", "status", "designStage?", "isRequiredDeliverable"],
            apiPath: "/api/realEstate/projectDocument",
            panelRoute: "/realEstate/projectDocuments",
            actions: ["submitForReview", "approve", "reject", "supersede", "markAsBuilt"],
            position: {x: 1320, y: 640},
        },
        {
            id: "DesignStage",
            label: "DesignStage",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Design phase gate for the project.",
            keyFields: ["project", "name", "status"],
            apiPath: "/api/realEstate/designStage",
            panelRoute: "/realEstate/designStages",
            position: {x: 1320, y: 160},
        },
        {
            id: "Milestone",
            label: "Milestone",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Project milestone with slippage detection via cron.",
            keyFields: ["project", "title", "dueAt", "status"],
            apiPath: "/api/realEstate/milestone",
            panelRoute: "/realEstate/milestones",
            position: {x: 1080, y: 280},
        },
        {
            id: "ScheduleTask",
            label: "ScheduleTask",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Detailed schedule task under project delivery.",
            keyFields: ["project", "title", "startAt", "endAt", "status"],
            apiPath: "/api/realEstate/scheduleTask",
            panelRoute: "/realEstate/scheduleTasks",
            position: {x: 1320, y: 280},
        },
        {
            id: "WorkPackage",
            label: "WorkPackage",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Scoped construction work — planned → active → completed.",
            keyFields: ["project", "constructor?", "status"],
            apiPath: "/api/realEstate/workPackage",
            panelRoute: "/realEstate/workPackages",
            actions: ["activate", "complete", "cancel"],
            position: {x: 1080, y: 400},
        },
        {
            id: "ConstructionContract",
            label: "ConstructionContract",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Contract with a constructor, often linked to a work package. Carries derived cost truth (approved VOs + certified claims totals).",
            keyFields: ["project", "constructor", "workPackage?", "status", "amount", "approvedVariationsTotal", "certifiedClaimsTotal"],
            apiPath: "/api/realEstate/constructionContract",
            panelRoute: "/realEstate/constructionContracts",
            position: {x: 1320, y: 400},
        },
        {
            id: "ProgressClaim",
            label: "ProgressClaim",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Payment claim against construction progress.",
            keyFields: ["project", "contract?", "amount", "status"],
            apiPath: "/api/realEstate/progressClaim",
            panelRoute: "/realEstate/progressClaims",
            position: {x: 1080, y: 520},
        },
        {
            id: "HandoverPackage",
            label: "HandoverPackage",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Handover documentation package at project/unit completion.",
            keyFields: ["project", "status"],
            apiPath: "/api/realEstate/handoverPackage",
            panelRoute: "/realEstate/handoverPackages",
            position: {x: 1320, y: 520},
        },
        {
            id: "ConstructionUpdate",
            label: "ConstructionUpdate",
            cluster: "delivery",
            module: "propertyManagement",
            description: "Progress update / media for project or edifice.",
            keyFields: ["project", "edifice?", "body", "media"],
            apiPath: "/api/realEstate/constructionUpdate",
            panelRoute: "/realEstate/constructionUpdates",
            position: {x: 1080, y: 640},
        },

        // ── Cost ────────────────────────────────────────────────────
        {
            id: "Budget",
            label: "Budget",
            cluster: "cost",
            module: "propertyManagement",
            description: "Kostenvoranschlag carrier — project budget lifecycle (draft → approval → lock → supersede) with eBKP-H/BKP method, classification standard and KV-Mutation revisions.",
            keyFields: ["project", "status", "method", "classificationStandard", "revisionNo", "supersedesBudget"],
            apiPath: "/api/realEstate/budget",
            panelRoute: "/realEstate/budgets",
            actions: ["submitForApproval", "approve", "lock", "supersede", "generateProgrammeFromBudget"],
            position: {x: 1560, y: 40},
        },
        {
            id: "BoqItem",
            label: "BoqItem",
            cluster: "cost",
            module: "propertyManagement",
            description: "Bill of quantities line under a budget.",
            keyFields: ["budget", "plannedRate", "plannedAmount", "actualAmount", "classificationStandard", "classificationCode", "elementCode"],
            apiPath: "/api/realEstate/boqItem",
            panelRoute: "/realEstate/boqItems",
            position: {x: 1560, y: 160},
        },
        {
            id: "CostClassification",
            label: "CostClassification",
            cluster: "cost",
            module: "propertyManagement",
            description: "Swiss cost-standard reference data (eBKP-H / BKP / NPK / SIA). Seeded per company; deactivate to retire.",
            keyFields: ["standard", "code", "parentCode", "level", "title", "active"],
            apiPath: "/api/realEstate/costClassification",
            panelRoute: "/realEstate/costClassifications",
            actions: ["deactivate", "activate"],
            position: {x: 1560, y: 280},
        },
        {
            id: "EstimateComparison",
            label: "EstimateComparison",
            cluster: "cost",
            module: "propertyManagement",
            description: "Read-model (no collection): Kostenermittlung eBKP-H — benchmarks the same classificationCode across projects/edifices (min/max/avg/total planned amount).",
            keyFields: ["standard", "code", "entries[]"],
            apiPath: "/api/realEstate/estimateComparison",
            panelRoute: "/realEstate/estimateComparison",
            position: {x: 1560, y: 400},
        },

        // ── Tendering ───────────────────────────────────────────────
        {
            id: "Specification",
            label: "Specification",
            cluster: "cost",
            module: "propertyManagement",
            description: "Leistungsverzeichnis (LV) header — Devisierung per NPK/custom. Lifecycle draft → issued → tender_ready → awarded → archived; can import NPK positions from CostClassification.",
            keyFields: ["project", "standard", "status", "totalEstimated"],
            apiPath: "/api/realEstate/specification",
            panelRoute: "/realEstate/specifications",
            actions: ["issue", "markTenderReady", "award", "archive", "importNpkPositions"],
            position: {x: 2040, y: 40},
        },
        {
            id: "SpecificationItem",
            label: "SpecificationItem",
            cluster: "cost",
            module: "propertyManagement",
            description: "LV position (Leistungsverzeichnis-Position) under a Specification. NPK chapter/position or R-Position (free), quantity × unitPrice = lineTotal.",
            keyFields: ["specification", "npkPosition", "isRPosition", "quantity", "unitPrice", "lineTotal", "classificationCode"],
            apiPath: "/api/realEstate/specificationItem",
            panelRoute: "/realEstate/specificationItems",
            actions: ["cancel"],
            position: {x: 2040, y: 200},
        },
        {
            id: "Tender",
            label: "Tender",
            cluster: "cost",
            module: "propertyManagement",
            description: "Ausschreibung — tendering of a Specification. Lifecycle draft → published → closing → closed → awarded | cancelled; deadline cron auto-closes and reminds.",
            keyFields: ["project", "specification", "trades", "submissionDeadline", "status"],
            apiPath: "/api/realEstate/tender",
            panelRoute: "/realEstate/tenders",
            actions: ["publish", "closeSubmissions", "award", "cancel", "reissue"],
            position: {x: 2040, y: 360},
        },
        {
            id: "TenderInvitation",
            label: "TenderInvitation",
            cluster: "cost",
            module: "propertyManagement",
            description: "Invited Constructor per Tender with a Bauplattform portalAccessToken. Lifecycle invited → viewing → submitted → declined | withdrawn.",
            keyFields: ["tender", "constructorRef", "portalAccessToken", "status"],
            apiPath: "/api/realEstate/tenderInvitation",
            panelRoute: "/realEstate/tenderInvitations",
            actions: ["decline", "withdraw", "resend"],
            position: {x: 2040, y: 520},
        },
        {
            id: "Bid",
            label: "Bid",
            cluster: "cost",
            module: "propertyManagement",
            description: "Angebot / TenderResponse — a contractor's priced offer. Submitted via the token-scoped Bauplattform portal or internally. Lifecycle draft → submitted → shortlisted → awarded | rejected | withdrawn.",
            keyFields: ["tender", "constructorRef", "total", "status", "submittedAt"],
            apiPath: "/api/realEstate/bid",
            panelRoute: "/realEstate/bids",
            actions: ["submit", "withdraw", "shortlist", "reject", "award"],
            position: {x: 2520, y: 360},
        },
        {
            id: "BidLine",
            label: "BidLine",
            cluster: "cost",
            module: "propertyManagement",
            description: "Priced line of a Bid against a SpecificationItem (LV position). quantity × unitPrice = lineTotal.",
            keyFields: ["bid", "specificationItem", "quantity", "unitPrice", "lineTotal"],
            apiPath: "/api/realEstate/bidLine",
            panelRoute: "/realEstate/bidLines",
            position: {x: 2520, y: 520},
        },
        {
            id: "BidComparison",
            label: "BidComparison",
            cluster: "cost",
            module: "propertyManagement",
            description: "Read-model (no collection): Angebotsvergleich — ranks a tender's bids by weighted price/quality/completeness score and recommends an award.",
            keyFields: ["tenderId", "rows[]", "recommendedBidId"],
            apiPath: "/api/realEstate/bidComparison",
            panelRoute: "/realEstate/bidComparison",
            position: {x: 2520, y: 680},
        },
        {
            id: "ApprovalWorkflow",
            label: "ApprovalWorkflow",
            cluster: "cost",
            module: "propertyManagement",
            description: "Freigabeprozess config (bounded to finance docs): primary approver role + escalation role required above a threshold amount.",
            keyFields: ["documentType", "approverRole", "thresholdAmount", "escalationRole", "active"],
            apiPath: "/api/realEstate/approvalWorkflow",
            panelRoute: "/realEstate/approvalWorkflows",
            position: {x: 3000, y: 40},
        },
        {
            id: "ApprovalRequest",
            label: "ApprovalRequest",
            cluster: "cost",
            module: "propertyManagement",
            description: "Bounded approval engine instance over a finance document. Lifecycle pending → approved | rejected | cancelled with primary → escalation stages driven by the workflow threshold.",
            keyFields: ["documentType", "targetType", "targetId", "amount", "currentStage", "status"],
            apiPath: "/api/realEstate/approvalRequest",
            panelRoute: "/realEstate/approvalRequests",
            actions: ["visa", "approve", "reject", "escalate", "recall"],
            position: {x: 3000, y: 200},
        },
        {
            id: "ContractorInvoice",
            label: "ContractorInvoice",
            cluster: "cost",
            module: "propertyManagement",
            description: "Unternehmerrechnung coded to a BKP account. Lifecycle received → under_review → approved → paid | rejected | disputed. Source manual or ap_inbox (from IncomingInvoice).",
            keyFields: ["constructorRef", "grossAmount", "bkpAccountCode", "qrBillReference", "status"],
            apiPath: "/api/realEstate/contractorInvoice",
            panelRoute: "/realEstate/contractorInvoices",
            actions: ["submitForApproval", "approve", "reject", "markPaid", "dispute"],
            position: {x: 3000, y: 360},
        },
        {
            id: "IncomingInvoice",
            label: "IncomingInvoice",
            cluster: "cost",
            module: "propertyManagement",
            description: "Kreditorenbewirtschaftung AP inbox. Scan → OCR (Swiss QR-bill parser, image OCR feature-flagged) → classify → route → post (spawns ContractorInvoice). Lifecycle inbox → classified → routed → posted | rejected.",
            keyFields: ["extractedSupplierName", "extractedAmount", "extractedQrReference", "matchedConstructor", "ocrStatus", "status"],
            apiPath: "/api/realEstate/incomingInvoice",
            panelRoute: "/realEstate/incomingInvoices",
            actions: ["runOcr", "classify", "route", "reject", "post"],
            position: {x: 3000, y: 520},
        },
        {
            id: "CostControl",
            label: "CostControl",
            cluster: "cost",
            module: "propertyManagement",
            description: "Read-model (no collection): Baukostenkontrolle — per-project BKP ledger of estimated (BoqItem) vs invoiced/paid (ContractorInvoice) with committed (CostCommitment) and certified (ProgressClaim) totals; variance = estimated − invoiced.",
            keyFields: ["projectId", "rows[] by bkp", "totals"],
            apiPath: "/api/realEstate/costControl",
            panelRoute: "/realEstate/costControl",
            position: {x: 3480, y: 360},
        },
        {
            id: "Cockpit",
            label: "Cockpit",
            cluster: "cost",
            module: "propertyManagement",
            description: "Read-model (no collection): cross-project KPI cockpit with Ampel (traffic-light) status — cost variance %, open RFIs, delayed milestones, open tenders, approval backlog, unpaid approved invoices.",
            keyFields: ["scope", "kpis[] with ampel"],
            apiPath: "/api/realEstate/cockpit",
            panelRoute: "/realEstate/cockpit",
            position: {x: 3480, y: 680},
        },
        {
            id: "BimModel",
            label: "BimModel",
            cluster: "cost",
            module: "propertyManagement",
            description: "BIM2COST — IFC model for quantity takeoff. importIfc is feature-flagged (PM_BIM_IFC_ENABLED) with manual-quantity fallback; pushToEstimate creates/updates BoqItem plannedQty on a budget from BimQuantities.",
            keyFields: ["project", "version", "elementCount", "importStatus"],
            apiPath: "/api/realEstate/bimModel",
            panelRoute: "/realEstate/bimModels",
            actions: ["importIfc", "pushToEstimate"],
            position: {x: 3960, y: 40},
        },
        {
            id: "BimQuantity",
            label: "BimQuantity",
            cluster: "cost",
            module: "propertyManagement",
            description: "Quantity takeoff line of a BimModel mapped to an eBKP-H classificationCode; feeds BoqItem plannedQty via pushToEstimate.",
            keyFields: ["bimModel", "ifcElementType", "classificationCode", "quantity", "unitOfMeasure"],
            apiPath: "/api/realEstate/bimQuantity",
            panelRoute: "/realEstate/bimQuantities",
            position: {x: 3960, y: 200},
        },
        {
            id: "Analytics",
            label: "Analytics",
            cluster: "cost",
            module: "propertyManagement",
            description: "Read-model (no collection): Power BI dataset feed (§3.P) — flat cost fact table per project × BKP (estimated vs invoiced). SAP/Abacus export shapes live in erpExport.",
            keyFields: ["dataset", "rows[]"],
            apiPath: "/api/realEstate/analytics",
            panelRoute: "/realEstate/erpExport",
            position: {x: 3960, y: 360},
        },
        {
            id: "LiquidityPlan",
            label: "LiquidityPlan",
            cluster: "cost",
            module: "propertyManagement",
            description: "Liquiditätsplanung container over a horizon/granularity. rebuildFromSources regenerates outflow lines from contractor invoices bucketed by month (manual lines preserved).",
            keyFields: ["project", "horizonStart", "horizonEnd", "granularity"],
            apiPath: "/api/realEstate/liquidityPlan",
            panelRoute: "/realEstate/liquidityPlans",
            actions: ["rebuildFromSources"],
            position: {x: 3480, y: 40},
        },
        {
            id: "LiquidityLine",
            label: "LiquidityLine",
            cluster: "cost",
            module: "propertyManagement",
            description: "Planned/actual inflow or outflow bucket of a LiquidityPlan. source: owner_contract / payment_plan / cost_commitment / contractor_invoice / fee / manual.",
            keyFields: ["plan", "period", "direction", "source", "plannedAmount", "actualAmount"],
            apiPath: "/api/realEstate/liquidityLine",
            panelRoute: "/realEstate/liquidityLines",
            position: {x: 3480, y: 200},
        },
        {
            id: "FeeCalculation",
            label: "FeeCalculation",
            cluster: "cost",
            module: "propertyManagement",
            description: "Honorarberechnung — derived SIA fee for a ConsultantAppointment. recompute = basisAmount × feePercent × adjustmentFactor, capped. Lifecycle planned → earned → invoiced → paid.",
            keyFields: ["consultantAppointment", "basisAmount", "feePercent", "totalFee", "status"],
            apiPath: "/api/realEstate/feeCalculation",
            panelRoute: "/realEstate/feeCalculations",
            actions: ["recompute", "markEarned", "markInvoiced", "markPaid"],
            position: {x: 3480, y: 520},
        },
        {
            id: "CostCommitment",
            label: "CostCommitment",
            cluster: "cost",
            module: "propertyManagement",
            description: "Purchase order / commitment against planned cost.",
            keyFields: ["project", "committedAmount", "status"],
            apiPath: "/api/realEstate/costCommitment",
            panelRoute: "/realEstate/costCommitments",
            actions: ["issue", "close", "cancel"],
            position: {x: 1560, y: 280},
        },
        {
            id: "UnitCost",
            label: "UnitCost",
            cluster: "cost",
            module: "propertyManagement",
            description: "Cost line attributed to a unit (and optional constructor / BoQ / VO).",
            keyFields: ["unit", "project", "amount", "constructor?", "boqItem?"],
            apiPath: "/api/realEstate/unit/cost",
            panelRoute: "/realEstate/unitCosts",
            position: {x: 280, y: 460},
        },
        {
            id: "VariationOrder",
            label: "VariationOrder",
            cluster: "cost",
            module: "propertyManagement",
            description: "Contract variation (Nachtrag) affecting cost and sometimes snags/work. billVariations bills approved VOs singly or grouped under a billingReference.",
            keyFields: ["project", "costImpact", "status", "billedAt", "billingReference"],
            apiPath: "/api/realEstate/variationOrder",
            panelRoute: "/realEstate/variationOrders",
            actions: ["approveArchitect", "approveQs", "approveClient", "reject", "cancel", "billVariations"],
            position: {x: 1560, y: 400},
        },

        // ── Quality & HSE ───────────────────────────────────────────
        {
            id: "Inspection",
            label: "Inspection",
            cluster: "quality",
            module: "propertyManagement",
            description: "Unit inspection checklist run (optionally from a template).",
            keyFields: ["unit", "status", "checklistTemplate?"],
            apiPath: "/api/realEstate/unit/inspection",
            panelRoute: "/realEstate/inspections",
            position: {x: 280, y: 600},
        },
        {
            id: "ModificationRequest",
            label: "ModificationRequest",
            cluster: "quality",
            module: "propertyManagement",
            description: "Buyer/tenant change request on a unit — SLA tracked by cron.",
            keyFields: ["unit", "status", "cost"],
            apiPath: "/api/realEstate/unit/modificationRequest",
            panelRoute: "/realEstate/modificationRequests",
            position: {x: 280, y: 740},
        },
        {
            id: "Snag",
            label: "Snag",
            cluster: "quality",
            module: "propertyManagement",
            description: "Defect / punch-list item on a unit; may link to work package or VO.",
            keyFields: ["unit", "status", "workPackage?", "variationOrder?"],
            apiPath: "/api/realEstate/snag",
            panelRoute: "/realEstate/snags",
            position: {x: 40, y: 600},
        },
        {
            id: "Asset",
            label: "Asset",
            cluster: "quality",
            module: "propertyManagement",
            description: "Technical FM asset register (building component/equipment). Lifecycle planned/active/maintenance/retired.",
            keyFields: ["edifice", "category", "manufacturer", "serial", "lifecycleStatus"],
            apiPath: "/api/realEstate/asset",
            panelRoute: "/realEstate/assets",
            actions: ["activate", "setMaintenance", "retire"],
            position: {x: 520, y: 600},
        },
        {
            id: "MaintenancePlan",
            label: "MaintenancePlan",
            cluster: "quality",
            module: "propertyManagement",
            description: "Instandhaltung/Gebäudeunterhalt plan (preventive/statutory/renovation) with intervalDays + nextDueAt. maintenanceDue cron spawns work orders; generateWorkOrder does it on demand.",
            keyFields: ["asset", "planType", "intervalDays", "nextDueAt"],
            apiPath: "/api/realEstate/maintenancePlan",
            panelRoute: "/realEstate/maintenancePlans",
            actions: ["generateWorkOrder"],
            position: {x: 760, y: 600},
        },
        {
            id: "MaintenanceWorkOrder",
            label: "MaintenanceWorkOrder",
            cluster: "quality",
            module: "propertyManagement",
            description: "Maintenance work order. Lifecycle open → assigned → in_progress → done → verified → closed | cancelled.",
            keyFields: ["plan", "asset", "type", "assignee", "actualCost", "status"],
            apiPath: "/api/realEstate/maintenanceWorkOrder",
            panelRoute: "/realEstate/maintenanceWorkOrders",
            actions: ["assign", "start", "complete", "verify", "close", "cancel"],
            position: {x: 1000, y: 600},
        },
        {
            id: "PlanMarkup",
            label: "PlanMarkup",
            cluster: "quality",
            module: "propertyManagement",
            description: "Bauleitung 2D-plan marker on a ProjectDocument (defect/decision/order/pendency/info) with normalized geometry. Lifecycle open → in_progress → done | void. Can link a Snag/RFI/ScheduleTask.",
            keyFields: ["planDocument", "markerType", "geometryX", "geometryY", "status"],
            apiPath: "/api/realEstate/planMarkup",
            panelRoute: "/realEstate/planMarkups",
            actions: ["startProgress", "resolve", "reopen", "voidMarkup"],
            position: {x: 280, y: 600},
        },
        {
            id: "Rfi",
            label: "RFI",
            cluster: "quality",
            module: "propertyManagement",
            description: "Request for information during construction.",
            keyFields: ["project", "status"],
            apiPath: "/api/realEstate/rfi",
            panelRoute: "/realEstate/rfis",
            position: {x: 1560, y: 520},
        },
        {
            id: "Submittal",
            label: "Submittal",
            cluster: "quality",
            module: "propertyManagement",
            description: "Contractor submittal for review/approval.",
            keyFields: ["project", "status"],
            apiPath: "/api/realEstate/submittal",
            panelRoute: "/realEstate/submittals",
            position: {x: 1560, y: 640},
        },
        {
            id: "SafetyIncident",
            label: "SafetyIncident",
            cluster: "quality",
            module: "propertyManagement",
            description: "HSE incident record on a project site.",
            keyFields: ["project", "severity", "status"],
            apiPath: "/api/realEstate/safetyIncident",
            panelRoute: "/realEstate/safetyIncidents",
            position: {x: 1320, y: 640},
        },
        {
            id: "SiteDiary",
            label: "SiteDiary",
            cluster: "quality",
            module: "propertyManagement",
            description: "Daily site log for construction progress and conditions.",
            keyFields: ["project", "date", "notes"],
            apiPath: "/api/realEstate/siteDiary",
            panelRoute: "/realEstate/siteDiaries",
            position: {x: 1080, y: 760},
        },
        {
            id: "Warranty",
            label: "Warranty",
            cluster: "quality",
            module: "propertyManagement",
            description: "Post-handover warranty coverage.",
            keyFields: ["project", "expiresAt", "status"],
            apiPath: "/api/realEstate/warranty",
            panelRoute: "/realEstate/warranties",
            position: {x: 1320, y: 760},
        },
    ],
    edges: [
        // Portfolio hierarchy
        {id: "e-ed-pr", source: "Edifice", target: "Project", label: "in"},
        {id: "e-fl-ed", source: "Floor", target: "Edifice", label: "in"},
        {id: "e-un-fl", source: "Unit", target: "Floor", label: "on"},
        {id: "e-un-ed", source: "Unit", target: "Edifice", label: "in"},
        {id: "e-un-pr", source: "Unit", target: "Project", label: "project"},
        {id: "e-un-ut", source: "Unit", target: "UnitType", label: "type"},
        {id: "e-ut-cat", source: "UnitType", target: "UnitTypeCategory", label: "category"},
        {id: "e-ed-ctor", source: "Edifice", target: "Constructor", label: "builders"},
        {id: "e-uc-un", source: "UnitCost", target: "Unit", label: "costs"},

        // Sales
        {id: "e-lead-pr", source: "Lead", target: "Project", label: "for"},
        {id: "e-lead-un", source: "Lead", target: "Unit", label: "interest"},
        {id: "e-res-un", source: "Reservation", target: "Unit", label: "reserves"},
        {id: "e-sale-un", source: "Sale", target: "Unit", label: "sells"},
        {id: "e-sale-res", source: "Sale", target: "Reservation", label: "from"},
        {id: "e-pp-sale", source: "PaymentPlan", target: "Sale", label: "installments"},
        {id: "e-com-sale", source: "Commission", target: "Sale", label: "from sale"},
        {id: "e-com-res", source: "Commission", target: "Reservation", label: "from reservation"},

        // Leasing
        {id: "e-lease-un", source: "Lease", target: "Unit", label: "rents"},
        {id: "e-rp-lease", source: "RentalPayment", target: "Lease", label: "pays"},

        // Ops on unit
        {id: "e-insp-un", source: "Inspection", target: "Unit", label: "inspects"},
        {id: "e-mod-un", source: "ModificationRequest", target: "Unit", label: "changes"},
        {id: "e-snag-un", source: "Snag", target: "Unit", label: "defect on"},

        // Delivery / cost chain
        {id: "e-land-pr", source: "LandParcel", target: "Project", label: "for"},
        {id: "e-feas-pr", source: "FeasibilityStudy", target: "Project", label: "for"},
        {id: "e-perm-pr", source: "Permit", target: "Project", label: "for"},
        {id: "e-ds-pr", source: "DesignStage", target: "Project", label: "for"},
        {id: "e-pd-pr", source: "ProjectDocument", target: "Project", label: "for"},
        {id: "e-pd-ds", source: "ProjectDocument", target: "DesignStage", label: "deliverable of (gates completion)"},
        {id: "e-ms-pr", source: "Milestone", target: "Project", label: "for"},
        {id: "e-st-pr", source: "ScheduleTask", target: "Project", label: "for"},
        {id: "e-wp-pr", source: "WorkPackage", target: "Project", label: "for"},
        {id: "e-wp-ctor", source: "WorkPackage", target: "Constructor", label: "assigned"},
        {id: "e-cc-pr", source: "ConstructionContract", target: "Project", label: "for"},
        {id: "e-cc-ctor", source: "ConstructionContract", target: "Constructor", label: "with"},
        {id: "e-cc-wp", source: "ConstructionContract", target: "WorkPackage", label: "covers"},
        {id: "e-pc-cc", source: "ProgressClaim", target: "ConstructionContract", label: "claims (capped by value + approved VOs)"},
        {id: "e-vo-cc", source: "VariationOrder", target: "ConstructionContract", label: "adjusts cost truth"},
        {id: "e-ho-sale", source: "Sale", target: "HandoverPackage", label: "handover gated by"},
        {id: "e-ho-pr", source: "HandoverPackage", target: "Project", label: "for"},
        {id: "e-cu-pr", source: "ConstructionUpdate", target: "Project", label: "updates"},
        {id: "e-bud-pr", source: "Budget", target: "Project", label: "for"},
        {id: "e-boq-bud", source: "BoqItem", target: "Budget", label: "line of"},
        {id: "e-bud-cc", source: "Budget", target: "CostClassification", label: "classified by (eBKP-H/BKP)"},
        {id: "e-boq-cc", source: "BoqItem", target: "CostClassification", label: "coded by (element/BKP)"},
        {id: "e-ec-boq", source: "EstimateComparison", target: "BoqItem", label: "aggregates by code"},
        {id: "e-ec-cc", source: "EstimateComparison", target: "CostClassification", label: "labels via code"},
        {id: "e-spec-pr", source: "Specification", target: "Project", label: "for"},
        {id: "e-spec-wp", source: "Specification", target: "WorkPackage", label: "scopes"},
        {id: "e-spec-cc", source: "Specification", target: "CostClassification", label: "imports NPK positions"},
        {id: "e-specitem-spec", source: "SpecificationItem", target: "Specification", label: "position of"},
        {id: "e-specitem-cc", source: "SpecificationItem", target: "CostClassification", label: "coded by (eBKP/BKP)"},
        {id: "e-tnd-spec", source: "Tender", target: "Specification", label: "tenders"},
        {id: "e-tinv-tnd", source: "TenderInvitation", target: "Tender", label: "invited to"},
        {id: "e-tinv-con", source: "TenderInvitation", target: "Constructor", label: "invites"},
        {id: "e-bid-tnd", source: "Bid", target: "Tender", label: "offer for"},
        {id: "e-bid-tinv", source: "Bid", target: "TenderInvitation", label: "responds to"},
        {id: "e-bid-con", source: "Bid", target: "Constructor", label: "from"},
        {id: "e-bidl-bid", source: "BidLine", target: "Bid", label: "line of"},
        {id: "e-bidl-si", source: "BidLine", target: "SpecificationItem", label: "prices"},
        {id: "e-bcmp-tnd", source: "BidComparison", target: "Tender", label: "ranks bids of"},
        {id: "e-bcmp-bid", source: "BidComparison", target: "Bid", label: "scores"},
        {id: "e-apr-awf", source: "ApprovalRequest", target: "ApprovalWorkflow", label: "routed by"},
        {id: "e-cinv-con", source: "ContractorInvoice", target: "Constructor", label: "billed by"},
        {id: "e-cinv-cc", source: "ContractorInvoice", target: "ConstructionContract", label: "against"},
        {id: "e-cinv-pr", source: "ContractorInvoice", target: "Project", label: "on"},
        {id: "e-inv-cinv", source: "IncomingInvoice", target: "ContractorInvoice", label: "posts to"},
        {id: "e-inv-con", source: "IncomingInvoice", target: "Constructor", label: "matched to"},
        {id: "e-cc-boq", source: "CostControl", target: "BoqItem", label: "estimated from"},
        {id: "e-cc-cinv", source: "CostControl", target: "ContractorInvoice", label: "invoiced from"},
        {id: "e-liql-liq", source: "LiquidityLine", target: "LiquidityPlan", label: "line of"},
        {id: "e-liq-cinv", source: "LiquidityPlan", target: "ContractorInvoice", label: "outflows from"},
        {id: "e-fee-ca", source: "FeeCalculation", target: "ConsultantAppointment", label: "computed for"},
        {id: "e-pmk-pd", source: "PlanMarkup", target: "ProjectDocument", label: "marks up"},
        {id: "e-cockpit-cc", source: "Cockpit", target: "CostControl", label: "rolls up KPIs"},
        {id: "e-mpl-ast", source: "MaintenancePlan", target: "Asset", label: "maintains"},
        {id: "e-mwo-mpl", source: "MaintenanceWorkOrder", target: "MaintenancePlan", label: "spawned by"},
        {id: "e-mwo-ast", source: "MaintenanceWorkOrder", target: "Asset", label: "services"},
        {id: "e-ast-edi", source: "Asset", target: "Edifice", label: "installed in"},
        {id: "e-bimq-bim", source: "BimQuantity", target: "BimModel", label: "quantity of"},
        {id: "e-bim-boq", source: "BimModel", target: "BoqItem", label: "pushes quantities to"},
        {id: "e-bimq-cc", source: "BimQuantity", target: "CostClassification", label: "mapped to eBKP-H"},
        {id: "e-analytics-cinv", source: "Analytics", target: "ContractorInvoice", label: "BI facts from"},
        {id: "e-po-pr", source: "CostCommitment", target: "Project", label: "commits"},
        {id: "e-vo-pr", source: "VariationOrder", target: "Project", label: "varies"},
        {id: "e-rfi-pr", source: "Rfi", target: "Project", label: "asks"},
        {id: "e-sub-pr", source: "Submittal", target: "Project", label: "submits"},
        {id: "e-si-pr", source: "SafetyIncident", target: "Project", label: "on"},
        {id: "e-sd-pr", source: "SiteDiary", target: "Project", label: "logs"},
        {id: "e-war-pr", source: "Warranty", target: "Project", label: "covers"},
        {id: "e-snag-wp", source: "Snag", target: "WorkPackage", label: "may link"},
    ],
    flows: [
        {
            id: "pm-sales",
            title: "Sales pipeline",
            summary:
                "Lead → reserve unit (deposit) → convert to Sale (cash or payment plan) → commissions; unit status moves available → reserved → sold.",
            module: "propertyManagement",
            steps: [
                {
                    id: "ps-lead",
                    label: "Lead",
                    description: "Capture interest",
                    detail: "/api/realEstate/lead — linked to Project and optional Unit.",
                    position: {x: 0, y: 80},
                },
                {
                    id: "ps-reserve",
                    label: "Reservation",
                    description: "Deposit + expiry",
                    detail: "Unit → reserved_unit. Cron sends expiration reminders.",
                    position: {x: 240, y: 80},
                },
                {
                    id: "ps-sale",
                    label: "Sale",
                    description: "Cash or payment plan",
                    detail: "createCashSale / createPaymentPlanSale. Unit → sold_unit.",
                    position: {x: 480, y: 80},
                },
                {
                    id: "ps-plan",
                    label: "PaymentPlan",
                    description: "Installments",
                    detail: "Only for payment_type=payment_plan. Cron installment reminders.",
                    position: {x: 720, y: 80},
                },
                {
                    id: "ps-commission",
                    label: "Commission",
                    description: "Agent payout",
                    detail: "Commission from Sale or Reservation; tracked in commissions panel.",
                    position: {x: 960, y: 80},
                },
                {
                    id: "ps-handover",
                    label: "Handover",
                    description: "Keys / title",
                    detail: "Sale approval → handover / title transfer actions.",
                    position: {x: 1200, y: 80},
                },
            ],
            edges: [
                {id: "f-ps-1", source: "ps-lead", target: "ps-reserve"},
                {id: "f-ps-2", source: "ps-reserve", target: "ps-sale", label: "convert"},
                {id: "f-ps-3", source: "ps-sale", target: "ps-plan", label: "if plan"},
                {id: "f-ps-4", source: "ps-sale", target: "ps-commission"},
                {id: "f-ps-5", source: "ps-sale", target: "ps-handover"},
            ],
        },
        {
            id: "pm-lease",
            title: "Lease & rent",
            summary:
                "Available unit → Lease (unit rented) → RentalPayment schedule → mark paid / overdue / waived; terminate releases unit.",
            module: "propertyManagement",
            steps: [
                {
                    id: "pl-unit",
                    label: "Available unit",
                    description: "status = available_unit",
                    detail: "Unit must be free of active sale/reservation for leasing.",
                    position: {x: 40, y: 80},
                },
                {
                    id: "pl-lease",
                    label: "Create Lease",
                    description: "Tenant + rent + dates",
                    detail: "Unit → rented_unit. Managed under leases / rentalsHub.",
                    position: {x: 320, y: 80},
                },
                {
                    id: "pl-schedule",
                    label: "RentalPayments",
                    description: "Monthly schedule",
                    detail: "pending rows generated; rental maintenance cron tracks overdue.",
                    position: {x: 600, y: 80},
                },
                {
                    id: "pl-collect",
                    label: "Collect / waive",
                    description: "paid | overdue | waived",
                    detail: "Operators mark payments; overdue surfaces in rentals hub.",
                    position: {x: 880, y: 80},
                },
                {
                    id: "pl-end",
                    label: "Terminate / expire",
                    description: "Release unit",
                    detail: "Lease end returns unit toward available for next disposition.",
                    position: {x: 1160, y: 80},
                },
            ],
            edges: [
                {id: "f-pl-1", source: "pl-unit", target: "pl-lease"},
                {id: "f-pl-2", source: "pl-lease", target: "pl-schedule"},
                {id: "f-pl-3", source: "pl-schedule", target: "pl-collect"},
                {id: "f-pl-4", source: "pl-collect", target: "pl-end"},
            ],
        },
        {
            id: "pm-delivery",
            title: "Delivery & cost",
            summary:
                "Land/feasibility → permits & design → budget/BoQ/commitments → work packages & contracts → progress claims → handover / warranty.",
            module: "propertyManagement",
            steps: [
                {
                    id: "pd-plan",
                    label: "Plan",
                    description: "Land + feasibility",
                    detail: "LandParcel and FeasibilityStudy under the Project.",
                    position: {x: 0, y: 80},
                },
                {
                    id: "pd-permit",
                    label: "Permits & design",
                    description: "Regulatory + design stages",
                    detail: "Permit expiry cron; DesignStage gates.",
                    position: {x: 240, y: 80},
                },
                {
                    id: "pd-budget",
                    label: "Budget & BoQ",
                    description: "approve → lock",
                    detail: "Budget → BoqItem lines → CostCommitment POs.",
                    position: {x: 480, y: 80},
                },
                {
                    id: "pd-build",
                    label: "Build",
                    description: "WP + contracts",
                    detail: "WorkPackage + ConstructionContract with Constructor.",
                    position: {x: 720, y: 80},
                },
                {
                    id: "pd-claim",
                    label: "Progress claims",
                    description: "Pay for progress",
                    detail: "ProgressClaim against contract; RFI / Submittal / VO alongside.",
                    position: {x: 960, y: 80},
                },
                {
                    id: "pd-handover",
                    label: "Handover",
                    description: "Package + warranty",
                    detail: "HandoverPackage, CommissioningRecord, Warranty.",
                    position: {x: 1200, y: 80},
                },
            ],
            edges: [
                {id: "f-pd-1", source: "pd-plan", target: "pd-permit"},
                {id: "f-pd-2", source: "pd-permit", target: "pd-budget"},
                {id: "f-pd-3", source: "pd-budget", target: "pd-build"},
                {id: "f-pd-4", source: "pd-build", target: "pd-claim"},
                {id: "f-pd-5", source: "pd-claim", target: "pd-handover"},
            ],
        },
    ],
    capabilities: [
        {
            id: "propertyManagement",
            title: "Property Management",
            summary:
                "Real-estate portfolio, sales, leasing, construction delivery, cost control, and quality/HSE — panel under /realEstate/*, APIs under /api/realEstate/*.",
            offers: [
                {
                    title: "Portfolio hierarchy",
                    description: "Project → Edifice → Floor → Unit with UnitType typology and Constructors.",
                },
                {
                    title: "Sales pipeline",
                    description: "Leads, reservations, cash/payment-plan sales, commissions, contracts hub.",
                },
                {
                    title: "Leasing",
                    description: "Leases, rental payment schedules, rentals hub, unit status rented.",
                },
                {
                    title: "Delivery & cost",
                    description: "Permits, milestones, budgets, BoQ, commitments, work packages, contracts, claims, handover.",
                },
                {
                    title: "Quality & HSE",
                    description: "Inspections, modification requests, snags, RFIs, submittals, site diary, safety incidents, warranties.",
                },
            ],
            apis: [
                "/api/realEstate/project",
                "/api/realEstate/edifice",
                "/api/realEstate/unit",
                "/api/realEstate/unit/reservation",
                "/api/realEstate/unit/sale",
                "/api/realEstate/lease",
                "/api/realEstate/rentalPayment",
                "/api/realEstate/budget",
                "/api/realEstate/workPackage",
                "/api/realEstate/dashboard",
            ],
            crons: [
                "Reservation expiration reminders",
                "Payment-plan installment reminders",
                "Rental maintenance / overdue",
                "Permit expiry",
                "Milestone slippage",
                "Modification-request SLA",
            ],
            publicRoutes: [
                "/api/realEstate/marketingUnit",
                "/api/realEstate/marketingProjects",
                "/api/realEstate/marketingAvailability",
            ],
        },
    ],
};
